name: test workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Hello!!
        run: echo "Hello!! from ${{ github.workflow }}" triggers on ${{ github.event_name }} event on ${{ github.ref }} branch with ${{ github.sha }} commit, done by ${{ github.actor }}"